apiVersion: v1
kind: Pod
metadata:
  name: phpfpm-nginx
spec:
  containers:
    - name: php
      image: meir215/php:master
      ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: phpfpm-nginx
  ports:
  - name: http
    protocol: TCP
    nodePort: 30036
    port: 80
    targetPort: 80

---