apiVersion: v1
kind: Pod
metadata:
  name: phpfpm-nginx
spec:
  volumes:
    - name: shared-files
    - name: nginx-config-volume
      configMap:
        name: nginx-config
  containers:
    - name: php
      image: meir215/php:develop
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
      ports:
        - containerPort: 9000
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]
    - name: nginx
      image: meir215/phpnginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      ports:
        - containerPort: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.php: |
    events {}
    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.php index.html;

        server_name _;

        location / {
          try_files $uri $uri/ =404;
        }
        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }