apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  labels:
    app: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app
          image: meir215/php:develop
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5005

---

apiVersion: v1
kind: Service
metadata:
  name: php-svc
spec:
  type: NodePort
  selector:
    app: php-app
  ports:
    - protocol: TCP
      nodePort: 30035
      port: 5005
      targetPort: 5005