apiVersion: v1
kind: Pod
metadata:
  name: php-pod
spec:
  containers:
    - name: nginx-proxy
      image: meir215/phpnginx
      ports:
        - containerPort: 80
    - name: php
      image: meir215/php:master
      ports:
        - containerPort: 9000


---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      nodePort: 30036
      port: 80
      targetPort: 80