apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: nginx-proxy
          image: meir215/phpnginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        - name: php
          image: meir215/php:master
          imagePullPolicy: Always
          ports:
            - containerPort: 9000


---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx-proxy
  ports:
    - protocol: TCP
      nodePort: 30036
      port: 80
      targetPort: 80